services:
  - type: web
    name: pv-ai-telecom-backend
    env: python
    plan: free
    rootDir: backend_render
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
